email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate
  - jekyll-gist
  - jekyll-toc

# Exclude
exclude:
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - assets/
  - jekyll.sh
  - README.md

# Multiple Language Support
languages: ["zh-cn", "en"]
exclude_from_localizations: ["assets"]

# Markdown
kramdown:
    syntax_highlighter: rouge
    parse_block_html: true
    input: GFM